.github/workflows/build-and-deploy.yml, .github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Just like it says in the title :) 
In #25, the "Build and Deploy" workflow that is called by both "Deploy to Staging" and "Deploy to Production" workflows was edited to include secret values used to authenticate the Datadog terraform provider. However, the caller ("Deploy to X") workflows also need to be updated to pass the secrets as inputs to "Build and Deploy", since GitHub workflows that are triggered on `workflow_call` events [don't inherently have access to the caller's secrets](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)*.
*Calling the reused workflow with `secrets: inherit` isn't a viable option here because we area already using the `secrets` parameter as an object to supply a custom-named secret. Plus, I …
=> Ensure Datadog secrets are passed to "Build and Deploy" workflow

terraform/datadog_metrics.tf, terraform/main.tf, terraform/variables.tf
This PR contains a fix for the issue causing a [failing Terraform deployment](https://github.com/usdigitalresponse/grants-ingest/actions/runs/4613307469/jobs/8155147852) currently on `main`. 
The `datadog_metric_metadata` Terraform resource fails to provision metadata when the named metric is not one that Datadog knows about. In our case, this is because one particular metric (`grants_ingest.SplitGrantsGovXMLDB.opportunity.failed`) has never been emitted (although it's also possible that Datadog metrics expire after enough time has past since it was last seen). However, we want to be able to define metadata for our metrics in Terraform without needing to worry about if/when the metric has fired (such as when rolling out code that implements a new metric).
We use Terraform's `http` data …
=> Fix: `error creating metric metadata` in Terraform

terraform/variables.tf
Bumps the default version of the [datadog-lambda-extension](https://github.com/DataDog/datadog-lambda-extension) layer from 38 to 41.
- [v39](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v39)
- [v40](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v40)
- [v41](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v41)
- Full diff: [v38...v41](https://github.com/DataDog/datadog-lambda-extension/compare/v38...v41)
Verify that the terraform plan output includes a change for the `layers` attribute (showing a layer ARN ending in `:41`) for all `aws_lambda_function` resources.
- ~[ ] Added Unit tests~
=> Bump datadog-lambda-extension version from 38 to 41

terraform/main.tf
Follow-up PR to #47, it looks like we need an IAM policy in place to allow SES to write to our source data S3 bucket.  This PR should fix that.
=> fix: adding IAM policy that allows SES to write to source data S3 bucket

terraform/main.tf
I misread the AWS documentation (oops) and this IAM policy needs to be directly attached to the S3 bucket in question.  This PR fixes that.
=> fix: policy needs to be attached to source data S3 bucket

terraform/main.tf
One of the conditions for this S3 bucket policy is broken. This PR fixes it.
=> fix: typo in the S3 bucket policy receipt rule condition

terraform/local.tfvars, terraform/staging.tfvars
We're using the wrong domain for the staging SES email address for FFIS data. This PR fixes that.  I'm also setting a dummy value for local environments because this input parameter doesn't do any real validation outside of checking if the string looks like an email address or not.
=> fix: Correcting the SES email address for staging/local envs

terraform/main.tf
We need to define an active receipt rule set in SES for AWS to consider this a valid mailbox
=> fix: Designating FFIS receipt rule set as active in SES

service.datadog.yaml
This PR adds a `service.datadog.yaml` file that provides [service definition metadata](https://docs.datadoghq.com/tracing/service_catalog/service_metadata_structure) to Datadog. There's no impact to service behavior or infrastructure – this solely exists to facilitate service discovery in Datadog's [Service Catalog](https://docs.datadoghq.com/tracing/service_catalog/) offering.
Not really – follow up after merge to ensure the service/repo is represented in the Datadog Service Catalog.
=> Add Datadog service definition metadata

.github/workflows/build-and-deploy.yml, terraform/modules/DownloadFFISSpreadsheet/main.tf
Provides an explicit `principal` identifier for the SQS service in the Lambda triggers introduced in #73, which is causing Terraform to [fail](https://github.com/usdigitalresponse/grants-ingest/actions/runs/4918444417/jobs/8785188238) with errors like:
```
Error: adding Lambda Permission (grants_ingest-staging-DownloadFFISSpreadsheet/SQSQueueNotification): InvalidParameterValueException: The provided principal was invalid. Please check the principal and try again.
{
RespMetadata: {
StatusCode: 400,
RequestID: "bdac311b-8683-4904-b517-ab7a4e7fac7d"
},
Message_: "The provided principal was invalid. Please check the principal and try again.",
Type: "User"
}
with module.DownloadFFISSpreadsheet.module.lambda_function.aws_lambda_permission.current_version_triggers["SQSQueueNotification"],
on …
```
=> FIX: Specify SQS principal in Lambda trigger

cmd/PersistGrantsGovXMLDB/main.go
Fixes #110
This is a teeny tiny PR that moves the `awstrace.AppendMiddleware()` call in the `PersistGrantsGovXMLDB` handler's startup steps so that it's called a bit earlier – specifically, before the `aws.Config` value is passed to any AWS service clients. This is necessary because the Datadog `awstrace` behavior modifies the config value in order to auto-instrument tracing, and those modifications need to be present before it is used (copied) to configure individual clients.
Not much to do here since it's not quite possible to test Datadog locally. Tests (automated and manual) appear to be working just fine, and Lambda handlers' `main()` functions don't execute during unit tests.
=> Fix: Instrument AWS config before first use

.github/workflows/ci.yml, Taskfile.yml
This PR is a follow up to #284 and resolve additional caveats to ensuring build reproducibility. Specifically, it modifies `go build` options to string build-time metadata (including VCS information about the current environment, which is pretty much guaranteed to differ across CI/CD workflow executions) from compiled output.
Clarifying note: This PR avoids redundant build-and-upload operations in related to Lambda artifacts stored in S3 **during CI/CD**. The previous PR for the same issue, #284, resolved the issue for scenarios where `terraform plan` and/or `terraform apply` were executed in a **local environment** (in all cases except for possibly when git state had changed), and still constitutes an overall (if insufficient) improvement.
To verify that the new changes do produce …
=> Enhancement: Follow up to #284

terraform/production.s3.tfbackend, terraform/production.tfvars
This PR creates the necessary terraform config files for targeting the service's Production environment on AWS. These files are very similar to the existing files that target Staging, except that no Datadog metric metadata is specified, since that happens only needs to happen once, and is already configured for Staging deployments.
1. Cross fingers
2. ![image](https://j.gifs.com/7Lwo28.gif)
If things don't go as planned, it'll be okay – this is an initial service release with no existing downstream dependencies.
=> Add terraform configuration for Production

cmd/DownloadFFISSpreadsheet/handler.go, cmd/DownloadFFISSpreadsheet/main.go, cmd/SplitFFISSpreadsheet/sheet.go, terraform/datadog_dashboard.tf, terraform/datadog_notes/publishing_operations.md, terraform/outputs.tf, terraform/production.tfvars, terraform/staging.tfvars
This PR updates the Datadog service dashboard to provide a full overview of service health and general operational status. It also includes a few related modifications outside the direct scope of #301:
- Updates `DownloadFFISSpreadsheet` to emit a file size metric (a la `DownloadGrantsGovDB`)
- Registers notification handles for monitoring alerts (we'll probably want to update these to a monitoring integration and/or Slack, but I think the initial values are fine to start).
- Updates custom metric definitions to be comprehensive of all custom metrics emitted by the service
- Tags `cell_parsing_errors` metrics emitted by `SplitFFISSpreadsheet` with a `target` value that refers to the field targeted by the parsing operation
Check out the dashboard provisioned under a sandbox deployment …
=> Feat: Update Datadog service dashboard

cmd/PersistFFISData/dynamodb.go, cmd/PersistFFISData/dynamodb_test.go, terraform/datadog_dashboard.tf
This PR provides a fix for the bug described in #304. The solution involves updating the `PersistFFISData` Lambda function to generate new `revision` values as a conditional update value in the same manner as already implemented in `PersistGrantsGovXMLDB`.
This PR includes an additional fix for an incorrect dashboard metric that I noticed while debugging this issue.
1. Invoke `PersistFFISData` with an S3 object containing FFIS data that is not currently present in the configured DynamoDB table.
- Verify that after the invocation completes, a new item exists in the table that has `OpportunityID` and `Bill` values that match the values provided by the source S3 object.
- Verify that the new item also contains a non-null `revision` value.
- Note the `revision` value.
2. Modify the S3 object …
=> Fix: Generate fresh `revision` values when persisting FFIS data

.github/release-drafter.yml, terraform/main.tf, terraform/staging.s3.tfbackend, terraform/staging.tfvars
This PR migrates (recreates) the grants-ingest service in our staging environment upon merge to `main`.
There are ~two~ (edit: three) changes to this PR:
1. As part of the redeployment operation, we're removing the `staging` prefix from the namespace label used on resources. This isn't really useful for disambiguating anything, since AWS environments are fully isolated, and requires some odd workarounds to make cross-environment resources (like those in Datadog) target resources consistently across multiple environments (e.g. the Lambda `functionname` tag is inconsistent across environments when it's prefixed with the environment name).
2. Prevent dependabot from being cluttering up the release notes' contributors list.
3. Update the way we self-reference the email delivery bucket in its …
=> Maintenance: Migrate staging namespace

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Fixes missing permissions required for workflows that call the "Publish Terraform Plan" reusable workflow. 
Problem: Even though "Deploy Staging" and "Deploy Production" workflows don't need to comment on PRs, they use the "Publish Terraform Plan" workflow, which potentially does. Since GHA doesn't allow conditional permissions on reusable workflows, the callers need to grant the full scope of potentially-required permissions. This should be okay from a security perspective, since commenting on a PR in this context is not considered particularly sensitive, and any changes to the callers will need to be reviewed first.
=> Add missing `pull-requests: write` permissions

.github/workflows/build.yml, .github/workflows/code-scanning.yml
This PR avoids an error condition that surfaces when preparing the `bin/` directory during the "Build CLI" step of the reusable "Build" workflow.
Problem: The step `rm`s any preexisting `bin/grants-ingest` artifact as a precautionary step before building. In normal cases, no preexisting artifact should exist, so `rm bin/grants-ingest` fails with a "No such file or directory" error. 
Solution: Use `rm -f` to silence errors when the file does not exist.
**Update:** This PR also fixes an issue where the "Dependency Review" job was executing for non-PR workflows.
Problem: The "Dependency Review" job is part of the "Code Scanning" workflow, which runs on multiple events. However, dependency reviews are only useful when changes can be compared (i.e. during PRs). Because the workflow was missing …
=> Fix error when removing nonexistent artifact

.github/workflows/terraform-plan.yml
This PR fixes a typo introduced in #335 that manifests when encrypting Terraform plan file artifacts before upload. 
Problem: An extra character was being passed as an option to `gpg`.
Solution: Remove the character.
**Note:** Will merge without waiting for checks to pass, as the problematic step does not execute during PR events (which is why we missed this in the first place – TF plan artifacts are only needed for deployments).
=> Fix: typo in command when uploading TF plan

.github/workflows/publish-terraform-plan.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
This PR fixes two bugs introduced in #335 that show up in deployment workflows after a Terraform plan has been generated:
- Problem: When publishing a summary for the plan, the workflow attempts to create or update a PR comment. However, we're not working against a PR during deployment, so no PR number exists. Other related workflow steps are skipped when no PR number is provided, but I neglected to do so for this step.
- Solution: Add the same `if: inputs.write-comment && inputs.pr-number != ''` conditional check to the "Create or update comment" step of the "Publish Terraform Plan" workflow.
- Problem: The terraform provider plugin directory is currently added to the Terraform plan artifact. This [causes issues](https://stackoverflow.com/questions/70407525/terraform-gives-errors-failed-t …
=> Fix: Bugs during post-plan deployment steps

terraform/production.s3.tfbackend
This PR sets the DynamoDB table name used by Terraform to lock the Production environment during plan/apply operations. It enables initial release of the grants-ingest service 🎉
=> Set TF lock table name for Prod

terraform/production.tfvars
This PR removes the `/production/` path segment from SSM deployment parameters, which is a convention we moved away from since the last time this was configured in `production.tfvars`. The prefix now conforms to the actual paths used in this environment.
NB: Searched the codebase for other occurrences of `prod` and `production` and didn't find anything that should impact release.
=> Remove env segment from SSM path prefix in Production

terraform/modules/DownloadFFISSpreadsheet/main.tf, terraform/modules/DownloadGrantsGovDB/main.tf, terraform/modules/EnqueueFFISDownload/main.tf, terraform/modules/ExtractGrantsGovDBToXML/main.tf, terraform/modules/PersistFFISData/main.tf, terraform/modules/PersistGrantsGovXMLDB/main.tf, terraform/modules/ReceiveFFISEmail/main.tf, terraform/modules/SplitFFISSpreadsheet/main.tf, terraform/modules/SplitGrantsGovXMLDB/main.tf
This reverts commit 7e2e3fc51b50841c31645f91ad7ecb271e58870f. 
Since the #316 was from Dependabot, no updates to the usages of the upgrade module were made, which seems to cause issues in Terraform when planning against new environments. We should revisit this upgrade to change the input variables on the various `lambda_execution_policy` modules in a way that is more compatible. However, these changes shouldn't prevent launch.
=> Revert "Build(deps): Bump cloudposse/iam-policy/aws in /terraform (#316)"

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/deploy-production.yml, .github/workflows/qa.yml, .github/workflows/terraform-plan.yml
Previously, the "QA for Go" job (part of the reusable "QA" workflow) consisted of several steps that were executed sequentially. This PR breaks up the "QA for Go" job  into several smaller jobs that can be more easily parallelized, with a single "Prepare for Go QA" job dependency (which exists as an up-front job that optimizes subsequent ones). 
The net effect should be an overall speedup that means contributors don't need to wait as long for automated QA feedback.
Additionally, this PR adds the `github-actions` ecosystem to the Dependabot configuration for this repo, which will help keep dependencies for CI/CD automations up-to-date.
=> Parallelize QA jobs

.github/release-drafter.yml
This PR updates the automatic release notes configuration with a new exclusion rule. We currently have an exclusion rule of `dependabot`, but that doesn't seem to be working. My guess is this is due to dependabot showing up as `dependabot[bot]`, which is the new exclusion value.
This is done because we don't need to be thanking our robot overlords (yet) 🤖
=> Exclude dependabot[bot] from special thanks in release notes

terraform/main.tf, terraform/modules/PublishGrantEvents/main.tf
This PR addresses some issues related to resource naming conventions in AWS. Currently, although properly-tagged, SQS queue names are lacking a service-standard namespace prefix (which in our case is just the service name in Staging and Production environments). Having consistent resource-naming conventions makes things easier to find, debug, and govern, which is the impetus for this update.
Note: Renaming an SQS queue is a destructive action that requires the queue to be replaced. Therefore, it is generally important to deploy these changes between ingestion batches to avoid data loss. For these changes, we can mitigate risk in a few ways:
1. Production currently has no messages in the DLQ. As long as this change rolls out before another batch update (or between any batches where the DLQ …
=> Standardize SQS name prefixes

.github/workflows/build.yml, .github/workflows/code-scanning.yml, .github/workflows/dependabot-auto-approve.yml, .github/workflows/deploy-production.yml, .github/workflows/publish-terraform-plan.yml, .github/workflows/qa.yml, .github/workflows/release-drafter.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
This PR updates all third-party GitHub actions which were not previously pinned to a SHA version – they are now all pinned using SHAs and a comment annotating the semver version that corresponds to the SHA. The affected actions are enumerated by individual commits on this PR's branch (see commits with messages like `GHA: pin some-org/action-name`).
Additionally, this PR includes a new job in the `code-scanning.yml` workflow that detects and fails when workflow jobs are found without a pinned SHA version. If the workflow fails, the detected action(s) will be annotated on the job summary ([example](https://github.com/usdigitalresponse/grants-ingest/actions/runs/6329514334)).
These changes are intended to promote good security hygiene for our workflows, specifically by reducing the …
=> Pin all third-party GitHub actions to SHA version

cmd/DownloadGrantsGovDB/handler.go, cmd/DownloadGrantsGovDB/handler_test.go, cmd/DownloadGrantsGovDB/main.go, terraform/modules/DownloadGrantsGovDB/main.tf
Changes to the Grants.gov extract URL are causing the ingest service to fail. See ticket for detailed overview.
This PR updates the ingest service to handle this new URL for the Grants.gov extract.
=> Updates to account for new grants.gov URL pattern

cmd/DownloadGrantsGovDB/handler.go, terraform/datadog_dashboard.tf, terraform/datadog_monitors.tf
This PR fixes a few issues that are causing some of our Datadog monitors and dashboards to miss important operational issues. This was first noticed because monitors failed to alert us about failures related to #456, which on closer inspection also revealed that Lambda invocation success rates were being incorrectly represented on the service dashboard in Datadog.
All in all, there are three distinct problems that this PR addresses:
1. **Problem:** Datadog monitors (`Grant modification events failed to publish` and `DownloadGrantsGovDB failed`) failed to alert, despite the presence of DLQ messages and failed Lambda invocations.
- **Cause:** Datadog monitor queries are case-sensitive (which is unlike dashboard queries), and most AWS metrics are tagged with lowercase values. Because we …
=> Fix Datadog dashboard and monitor queries

cmd/PublishGrantEvents/handler.go, terraform/datadog_dashboard.tf
This PR adds a `type:create/update/delete` tag when emitting `PublishGrantEvents.event.published` metrics, and updates the dashboard to make use of the new tag granularity. In particular, it adds a "sunburst" (pie chart) widget to the Service Summary group, and modifies the existing Stream Item Processing Results widget to show "Published" totals by type.
Additionally, certain log outputs have been updated to include the event type in their structured data.
**Note for reviewers:** The `terraform/datadog_dashboard.tf` file on this branch contains changes to widgets unrelated to the ones that make use of the new metric tag. Specifically, the `widget_layout.y` coordinate offsets have been updated for all top-level widgets (i.e. group containers) – since the new widget takes up 3 additional …
=> Tag published event types in logs and metrics from `PublishGrantEvents` step

internal/awsHelpers/config.go
This PR contains changes that bypass customizations involving `github.com/aws/aws-sdk-go-v2/config` that provide LocalStack compatibility. The immediate goal is to resolve the issues noted in #496; if it does so, additional changes will be necessary to restore the ability to use LocalStack in dev environments.
=> Bypass config resolution for localstack

terraform/variables.tf
This PR upgrades the [`datadog-lambda-extension` layer](https://github.com/DataDog/datadog-lambda-extension), which may be contributing to the problems related to #496.
=> chore: upgrade datadog-lambda-extension 41 -> 51

.github/release-drafter.yml, .github/workflows/release-drafter.yml
This PR mirrors the changes to `.github/release-drafter.yml` in https://github.com/usdigitalresponse/usdr-gost/pull/2436, which remove the need to maintain a hard-coded year in that file, as well as adds a `# NOTES:` comment to the same file, which hopefully clarifies how the `release-drafter` action incorporates our precomputed `YYYY.inc` into the resulting release name and tag.
Additionally, this PR splits the `.github/workflows/release-drafter.yml` workflow file into two distinct jobs: one that labels open PRs, and another that creates/updates draft releases. This follows more recently-established conventions in other repositories; in particular it avoids modifying release notes in reaction to pull request events, which is unnecessary in the context of a PR.
=> Update release-drafter config

README.md
Adds some notes in the development prerequisites section of the README documentation to help those new to Go development get the correct version set up.
=> More development docs on Go version

cmd/SplitGrantsGovXMLDB/handler.go, cmd/SplitGrantsGovXMLDB/handler_test.go, cmd/SplitGrantsGovXMLDB/main.go, cmd/SplitGrantsGovXMLDB/types.go, cmd/SplitGrantsGovXMLDB/types_test.go, terraform/main.tf, terraform/modules/SplitGrantsGovXMLDB/main.tf, terraform/modules/SplitGrantsGovXMLDB/variables.tf
This PR refactors the `SplitGrantsGovXMLDB` lambda function so it ingests both grant opportunities and forecasted grants. 
As the lambda is scanning through the extracted grants.gov XML, it will now identify both `OpportunitySynopsisDetail_1_0` and `OpportunityForecastDetail_1_0` XML tags (whereas it previously only identified the former). These individual XML records will still be stashed as individual S3 files, but now with updated filenames to distinguish forecasted vs not. 
For now, we're also updating the filtering for the downstream `PersistGrantsGovXMLDB` lambda, so it only picks up on opportunities (not forecasted). Future work will enable forecasted grants through the rest of the pipeline. 
- Added/updated unit tests to ensure it processes forecasted grants
- I'd like to verify …
=> Ingest forecasted opportunities

openapi/openapi.yaml
This PR simply de-indents the YAML block under `components.schemas` by 2 spaces (from 4 spaces) in `openapi/openapi.yaml`. Although syntactically correct (all sub-objects of `components.schemas` are indented 4 spaces relative to the the parent block depth), the indentation is inconsistent with other blocks in the same file, and overall is inconsistent with recommended YAML formatting configurations currently under consideration in #894. 
The main motivation for this PR is to provide a reviewability improvement for #887, which also includes these same de-indentation changes. The idea is that if this PR is merged to `main` first, then the `openapi/openapi.yaml` diff in #887 will more accurately reflect the important modifications to that file.
=> Fix `openapi/openapi.yaml` over-indentation

go.mod, go.sum
Reverts usdigitalresponse/grants-ingest#915
Duplicate of #914
=> Revert "Chore [deps:gomod]: Bump github.com/aws/aws-sdk-go-v2 from 1.27.0 to 1.31.0"

.gitignore, .taskfiles/local.yml, .vscode/extensions.json, .vscode/settings.json, README.md, Taskfile.yml, openapi/openapi.yaml
This PR provides several changes aimed at improving developer experience for this repository:
- VS Code configuration: `.vscode/settings.json` and `.vscode/extensions.json` for recommended workspace settings and extensions, respectively.
- LocalStack workflow shortcuts via Taskfile: New `task local:` command group for streamlining common tasks
- README updates: Incorporates mentions of new Taskfile shortcuts
- Run `task clean`
- Start LocalStack (or restart if already running)
- Run `task local:from-scratch` and ensure that the command runs to completion (it will abort if an error is encountered)
- Run `awslocal s3api list-buckets` and verify that buckets specified in Terraform exist, along with a `local-terraform` bucket
- Run `task local:deploy` and ensure that the command runs to …
=> Developer experience enhancements

openapi/openapi.yaml
Added fiscal_year to Grant object, name and phone to GrantorContact object, award_date and project_start_date and forecast_creation_date to OpportunityMilestones object
=> Updated OpenAPI schema

.github/workflows/build.yml, .taskfiles/local.yml, Taskfile.yml
This PR fixes a build automation failure introduced in #894. That PR added a new Taskfile (`.taskfiles/local.yml`), which isn't bundled as a build source in `.github/workflows/build.yml`. Since it isn't available in build environments, the `task` command fails because it cannot locate the file. To fix this, there are two options:
1. Update the CI/CD build workflow to include `.taskfiles/local.yml` in build environments.
2. Update `Taskfile.yml` so that `.taskfiles/local.yml` is marked as an [optional include](https://taskfile.dev/usage/#optional-includes) so that `task` won't fail when the included file is unavailable.
Since nothing in `.taskfiles/local.yml` is strictly necessary outside of local development usage, this PR implements the second option.
=> Fix: missing taskfile source

cmd/SplitGrantsGovXMLDB/handler.go, cmd/SplitGrantsGovXMLDB/handler_test.go, cmd/SplitGrantsGovXMLDB/s3_test.go, cmd/SplitGrantsGovXMLDB/types.go, terraform/datadog_dashboard.tf, terraform/staging.tfvars
This PR fixes an edge case bug in `SplitGrantsGovXMLDB` exposed by #892, where a local `grantOpportunity` record will be uploaded to replace the currently-stored record when the local record's `LastUpdatedDate` matches that of the remote database record. 
Prior to #892, it would be extremely rare (if not altogether impossible) for a record's `LastUpdatedDate` (derived from date, i.e. always-midnight) to exactly match a corresponding S3 object's last-modified timestamp. Presumably, since S3 storage always occurs after the upstream modifications, the S3 storage would always come later. If anything, defaulting to replacing the object in these circumstances would likely be desirable since it would indicate some kind of inaccuracy in the underlying record and/or a previous execution of …
=> Fix: Skip s3 upload if record's last-modified time matches DB value

cmd/SplitGrantsGovXMLDB/dynamodb.go, cmd/SplitGrantsGovXMLDB/handler_test.go
This PR addresses a condition where a DynamoDB item has no `LastUpdatedDate` attribute, which can happen when FFIS data for a grant was ingested before the Grants.gov data for the same grant. Currently, this manifests as a time-parsing error, since an empty string cannot be parsed according to the expected `MMDDYYYY` format, which prevents `processRecord()` from moving forward with uploading the record to S3.
Cases where `LastUpdatedDate` cannot be parsed should generally result in an error, since we want to be alerted if records regularly contain un-parseable values. However, given that FFIS data may be ingested for a grant before Grants.gov data (although it should be fairly uncommon), we need to be able to handle the possibility that `LastUpdatedDate` may not yet be present for a grant …
=> Fix: Handle missing `LastUpdatedDate` attribute in DynamoDB items

.github/workflows/qa.yml
Reverts usdigitalresponse/grants-ingest#893 as a prerequisite for running CI on #942 .
=> Revert "Pin staticcheck version to 2023.1.6"

README.md, go.mod, go.sum
Chore PR that upgrades Go to v1.23.2 (current latest stable).
Tested as outlined in #909. Confirmed that unit tests and functional tests still run successfully and all dependencies are compatible.
=> Upgrade to Go v1.23.2

.github/workflows/code-scanning.yml
This PR allow-lists two new endpoints, the absence of which are currently causing the `dependency-review` job to fail in our CI pipeline. See https://github.com/actions/dependency-review-action/issues/609 for more details.
=> Fix blocked network requests for `dependency-review` GHA job
